uploads = []
generated = []

[[outputs]]
id = "Xqd8ksxYn-7LeJK7cdFW3"
uri = "file://DEVELOPER.md"
type = "text"
title = "Where You Dey? — Developer Guide"

[[outputs]]
id = "Y2om45eNaLS2SisF5UMRF"
uri = "file://where-you-dey.tar.gz"
type = "unspecified"
title = "Where You Dey — Full Source Code"
